// Simple script to populate the jobs table from a CSV file.

document.addEventListener('DOMContentLoaded', () => {
  // Fetch the CSV data.  By default this script loads a local jobs.csv file.
  // Fetch data from the local csv that is generated by the Action tab.
fetch("jobs.csv")
  .then(r => r.text())
  .then(csvText => {
      // Split the data into lines and ignore empty lines.
      const rows = data
        .trim()
        .split(/\r?\n/)
        .filter((line) => line.length > 0);

      if (rows.length <= 1) return;

      // A regular expression to split CSV values by commas that are not inside quotes.
      const csvSplit = /,(?=(?:[^"]*"[^"]*")*[^"]*$)/;

      // Skip the header row (index 0).
      const tbody = document.getElementById('jobs-tbody');
      for (let i = 1; i < rows.length; i++) {
        const cols = rows[i]
          .split(csvSplit)
          .map((c) => c.replace(/^"|"$/g, '').trim());

        const tr = document.createElement('tr');

        // Company
        const companyCell = document.createElement('td');
        companyCell.textContent = cols[0];
        tr.appendChild(companyCell);

        // Role
        const roleCell = document.createElement('td');
        roleCell.textContent = cols[1];
        tr.appendChild(roleCell);

        // Experience
        const expCell = document.createElement('td');
        expCell.textContent = cols[2];
        tr.appendChild(expCell);

        // Location
        const locCell = document.createElement('td');
        locCell.textContent = cols[3];
        tr.appendChild(locCell);

        // Link (last column)
        const linkCell = document.createElement('td');
        const link = document.createElement('a');
        link.href = cols[4];
        link.target = '_blank';
        link.rel = 'noopener noreferrer';
        link.textContent = 'Apply';
        linkCell.appendChild(link);
        tr.appendChild(linkCell);

        tbody.appendChild(tr);
      }
    })
    .catch((err) => {
      console.error('Error loading jobs:', err);
    });
});