name: Weekly job scrape

on:
  schedule:
    # GitHub Actions runs in UTC. 08:00 CET == 07:00 UTC in winter, 06:00 UTC in summer (CEST).
    # Run twice to straddle DST; it’s cheap for a small repo.
    - cron: "0 6 * * 6"   # Saturdays 06:00 UTC (covers CEST ≈ 08:00 local)
    - cron: "0 7 * * 6"   # Saturdays 07:00 UTC (covers CET ≈ 08:00 local)
  workflow_dispatch: {}   # allow manual run

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt

      - name: Run scraper
        env:
          # Optional: set to your published Google Sheet CSV if you prefer to read companies from a sheet
          SHEET2_CSV: ""
        run: |
          python scraper/scrape.py

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add scraper/Jobs.csv
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "Update Jobs.csv [auto]"
            git push
          fi
